mode: internal_5fold
internal_csv: /home/hxm/label/HER2/HER2_internal.csv
external_csv: /home/hxm/label/HER2/zssy_her2_label.csv
wsi_root: /home/hxm/data/HER2/WSI/512_R50_HER2_all/
mri_root: /home/hxm/data/HER2/MRI/preprocess/MRI_64_padding_all_h5/
output_dir: /home/hxm/model/IADA_released/runs/her2_iada

n_classes: 2
folds: 5
epochs: 100
batch_size: 2
lr: 1.0e-4
weight_decay: 0.0
seed: 2021

wsi_input_dim: 1024
wsi_embed_dim: 512
mri_out_dim: 512
latent_dim: 256
dropout: 0.25

alpha: 0.2
beta: 0.1
lambda_reg: 2.0e-2
focal_gamma: 1.0
focal_alpha: 0.25
use_dgm: true
grad_clip: 0.0
